version: "3.7"

networks:
  web:
    external: true

services:
  caddy:
    # image: caddy:latest
    build: ./dns-dockerfile
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SSD_BASE_PATH}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${SSD_BASE_PATH}/caddy/data/:/data
      - ${SSD_BASE_PATH}/caddy/config:/config
    environment:
      - CF_API_TOKEN
      - DOMAIN_NAME
    networks:
      - web
