version: '3.7'

networks:
  invoiceninja:
  web:
    external: true

services:
  ninja_proxy:
    image: nginx
    # image: caddy
    container_name: ninja_proxy
    restart: always
    env_file: env
    volumes:
      # Vhost configuration
      # - ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - ninja_app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    # ports: 
    #   - "80:80"
    #   - "443:443"
    expose:
      - "80"
      - "443"
    networks:
      - invoiceninja
      - web
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  ninja_app:
    image: invoiceninja/invoiceninja:5
    container_name: ninja_app
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./config/shutdown.sh:/usr/local/bin/shutdown.sh
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - ninja_db
    networks: 
      - invoiceninja
      - web
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip

  ninja_db:
    image: mysql:5
    container_name: ninja_db
#    For auto DB backups comment out image and use the build block below
#    build:
#      context: ./config/mysql
    ports:
      - "3305:3306"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=ninja
    volumes:
      - /data/invoice/data:/var/lib/mysql:rw,delegated

      # remove comments for next 4 lines if you want auto sql backups
      #- ./docker/mysql/bak:/backups:rw
      #- ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      #- ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      #- ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
    networks:
      - invoiceninja
      - web
    extra_hosts:
      - "in5.localhost:192.168.0.124 " #host and ip
