version: "3.7"

networks:
  web:
    external: true

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      - web
    restart: unless-stopped
    domainname: jeffslord.com
    #hostname: pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # cap_add:
    #   - NET_ADMIN
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8085:80/tcp'
    volumes:
      - ${SSD_BASE_PATH}/pihole/:/etc/pihole/
      - ${SSD_BASE_PATH}/pihole/dnsmasqd:/etc/dnsmasq.d/
    environment:
      ServerIP: 192.168.1.24
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.jeffslord.com
      VIRTUAL_PORT: 80
      TZ: 'America/Chicago'
      # DNS1: 127.0.0.1
      # DNS2: 1.1.1.1
      WEBPASSWORD: ${PIHOLE_PASS}
