version: "3.7"

networks:
  web:
    external: true

services:
  # groceries
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    networks:
      - web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ${SSD_BASE_PATH}/grocy/config:/config
    expose:
      - "9283"
    restart: unless-stopped
