version: "3"
services:
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
    restart: unless-stopped

      # for ddclient cloudflare config
      #protocol=cloudflare          ## 
      #server=fqdn.of.service       ## defaults to api.cloudflare.com/client/v4
      #login=service-login          ## login name and password  registered with the service
      #password=service-password    ##
      #fully.qualified.host         ## the host registered with the service.
