version: '3.2'
services:
  mc-rlcraft:
    image: itzg/minecraft-server
    container_name: mc-rlcraft
    ports:
       - "25590:25565"
    environment:
      EULA: "true"
      #TYPE: "CURSEFORGE"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      FORGEVERSION: "14.23.5.2838"
      #RCON_PASSWORD: "testing"
      #RCON_PORT: 28016
      #CF_SERVER_MOD: "rlcraft_2-8-2.zip"
      #CF_SERVER_MOD: "https://www.curseforge.com/minecraft/modpacks/rlcraft/files"
      GENERIC_PACK: "rlcraft_2-8-2.zip"
      LEVEL: "world1"
      MAX_MEMORY: "16G"
      #USE_MODPACK_START_SCRIPT: "false"
    volumes:
      - /home/server/volumes/minecraft/rlcraft_2-8-2/data/:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.mc_rlcraft.rule=Host(`mcrlcraft.jeffslord.com`)
      - traefik.http.services.mc_rlcraft.loadbalancer.server.port=25565
      - traefik.http.routers.mc_rlcraft.tls=true
      - traefik.http.routers.mc_rlcraft.tls.certresolver=myresolver
      - traefik.http.routers.mc_rlcraft.entrypoints=mc

  web:
    image: itzg/rcon
    container_name: mc-rlcraft-rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      #RWA_RCON_HOST: mc-rlcraft
      #RWA_RCON_PASSWORD: minecraft
    ports:
      - "4326:4326"
      - "4327:4327"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mc_rcon.rule=Host(`mcrlcraftrcon.jeffslord.com`)
      - traefik.http.services.mc_rcon.loadbalancer.server.port=4326
      - traefik.http.routers.mc_rcon.tls=true
      - traefik.http.routers.mc_rcon.tls.certresolver=myresolver
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
