version: '3'

services:
  terraria:
    image: beardedio/terraria:tshock-latest
    container_name: terraria
    ports:
      - '7777:7777'
    restart: unless-stopped
    environment:
      - world=test-world.wld
    volumes:
            #- $HOME/terraria/config:/config
      - /home/server/volumes/terraria/config:/config
        #- /home/server/volumes/terraria/tshock/ServerPlugins:/tshock/ServerPlugins
    tty: true
    stdin_open: true
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.terraria.rule=Host(`terraria.jeffslord.com`)
      - traefik.http.services.terraria.loadbalancer.server.port=7777
      - traefik.http.routers.terraria.tls=true
      - traefik.http.routers.terraria.tls.certresolver=myresolver
      - traefik.http.routers.terraria.entrypoints=web

networks:
 traefik:
   external: true

