services:
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      VERBOSITY: -vv #optional
    volumes:
      - /var/log:/var/log:ro
      - ${SSD_PATH}/fail2ban/config:/config
      - ${SSD_PATH}/media-system/sonarr/config/logs:/remotelogs/sonarr:ro
      - ${SSD_PATH}/media-system/radarr/config/logs:/remotelogs/radarr:ro
      - ${SSD_PATH}/media-system/plex/config/Library/Application Support/Plex Media Server/Logs:/remotelogs/plex:ro
      - ${SSD_PATH}/media-system/jellyfin/config/log:/remotelogs/jellyfin:ro
      - ${SSD_PATH}/media-system/prowlarr/config/logs:/remotelogs/prowlarr:ro
      # - ${SSD_PATH}/media-system/:/remotelogs/flaresolverr:ro
      - ${SSD_PATH}/media-system/qbittorrent/config/data/logs:/remotelogs/qbittorrent:ro
      - ${SSD_PATH}/media-system/ombi/config/Logs:/remotelogs/ombi:ro
      - ${SSD_PATH}/media-system/filebrowswer/config:/remotelogs/filebrowser:ro
      # - /path/to/airsonic/log:/remotelogs/airsonic:ro #optional
      # - /path/to/apache2/log:/remotelogs/apache2:ro #optional
      # - /path/to/authelia/log:/remotelogs/authelia:ro #optional
      # - /path/to/emby/log:/remotelogs/emby:ro #optional
      # - /path/to/filebrowser/log:/remotelogs/filebrowser:ro #optional
      # - /path/to/homeassistant/log:/remotelogs/homeassistant:ro #optional
      # - /path/to/lighttpd/log:/remotelogs/lighttpd:ro #optional
      # - /path/to/nextcloud/log:/remotelogs/nextcloud:ro #optional
      # - /path/to/nginx/log:/remotelogs/nginx:ro #optional
      # - /path/to/nzbget/log:/remotelogs/nzbget:ro #optional
      # - /path/to/overseerr/log:/remotelogs/overseerr:ro #optional
      # - /path/to/prowlarr/log:/remotelogs/prowlarr:ro #optional
      # - /path/to/radarr/log:/remotelogs/radarr:ro #optional
      # - /path/to/sabnzbd/log:/remotelogs/sabnzbd:ro #optional
      # - /path/to/sonarr/log:/remotelogs/sonarr:ro #optional
      # - /path/to/unificontroller/log:/remotelogs/unificontroller:ro #optional
      # - /path/to/vaultwarden/log:/remotelogs/vaultwarden:ro #optional
