version: "3"
services:
  minecraft-server:
    ports:
      - "25565:25565"

    environment:
      - EULA=TRUE
      - TYPE=FTB
      #- FORGEVERSION=14.23.4.2707
      - FTB_SERVER_MOD=http://minecraft.curseforge.com/projects/sevtech-ages/files/2570735/download
      #- MODPACK= ../modpacks/sevtech.zip
      - LEVEL=world
      - MAX_MEMORY="6G"
    volumes:
      - /home/server/Servers/minecraft/data/sevtech:/data

    image: itzg/minecraft-server

    container_name: mc-sevtech

    tty: true
