version: '3.2'
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: mc-valhelsia3
    ports:
    #  - "25565:25565"
    #  - "25575:25575"
       - "25590:25565"
    environment:
      EULA: "true"
      TYPE: "CURSEFORGE"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      #- CF_SERVER_MOD=https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/download/2791604
      CF_SERVER_MOD: "Valhelsia_SERVER-3.0.18.zip"
      LEVEL: "world1_3.0.18"
      MAX_MEMORY: "18G"
      #PROXY: mc_e2e.jeffslord.com
      
    volumes:
      - /home/server/volumes/minecraft/valhelsia3/data/:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.mc_valhelsia3.rule=Host(`mc_valhelsia3.jeffslord.com`)
      - traefik.http.services.mc_valhelsia3.loadbalancer.server.port=25565
      - traefik.http.routers.mc_valhelsia3.tls=true
      - traefik.http.routers.mc_valhelsia3.tls.certresolver=myresolver
#      - traefik.tcp.routers.minecraft.entrypoints=minecraft
#      - traefik.tcp.routers.minecraft.rule=HostSNI(`*`)
#      - traefik.tcp.services.minecraft.loadbalancer.server.port=25565
    
    
#    bungeecord:
#      image: itzg/bungeecord
#      ports:
#        - 25577:25577
#      volumes:
#        - ./config.yml:/server/config.ymlz

#  router:
#    image: itzg/mc-router
#    container_name: mc-router
#    ports:
#      - 25565:25565
#    command: --mapping=mc_e2e.jeffslord.com=mc-e2e-176a:25565
#    networks:
#      - traefik
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.mc_e2e.rule=Host(`mc_e2e.jeffslord.com`)
#      - traefik.http.services.mc_e2e.loadbalancer.server.port=25565

networks:
  traefik:
    external: true
